"""Create ratings table

Revision ID: c6baa58eb13a
Revises: 402aac34c086
Create Date: 2025-05-27 20:25:06.886790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6baa58eb13a'
down_revision: Union[str, None] = '402aac34c086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_ratings_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], name=op.f('fk_ratings_lender_id_lenders')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
