"""Create records table

Revision ID: e42096178a4e
Revises: 1633bc45ec0d
Create Date: 2025-05-27 20:19:29.523204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42096178a4e'
down_revision: Union[str, None] = '1633bc45ec0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('current_sales', sa.Float(), nullable=True),
    sa.Column('current_costs', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('asset_value', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Float(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_records_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
